### ISSUE TITLE
Register/login notice does not come up on unregistered users' appearance

### ISSUE THREAD

**Issue by hexchain** [games647/FlexibleLogin#10]
Using 0.4.1.

```
[20:27:54] [pool-2-thread-1/ERROR] [Sponge]: The Scheduler tried to run the task flexiblelogin-A-0 owned by Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.4}, but an error occured.
java.lang.NullPointerException
        at com.github.games647.flexiblelogin.listener.PlayerConnectionListener.lambda$onPlayerJoin$0(PlayerConnectionListener.java:34) ~[PlayerConnectionListener.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$9(Task.java:138) ~[Task$Builder.class:1.8-1577-3.0.0-BETA-1000]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$55(SchedulerBase.java:177) ~[SchedulerBase.class:1.8-1577-3.0.0-BETA-1000]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by games647** [comment]
If you try to implement a new feature, you always break something that worked before. :disappointed:
