### ISSUE TITLE
How i can connect with database?

### ISSUE THREAD

**Issue by wallxq** [games647/FlexibleLogin#103]
I have mysql (phpmyadmin) database and i cant connect. I must change only this? 
sqlConfiguration {
# Database name
    database=
    # Password in order to login
    password=""
    # Path where the database is located. This can be a file path (h2/SQLite) or an IP/Domain (MySQL/MariaDB)
    path="ip?"
    # Port for example MySQL connections
    port=3306
    # SQL server type. You can choose between h2, SQLite and MySQL/MariaDB
    type=MySQL/MariaDB
    # It's strongly recommended to enable SSL and setup a SSL certificate if the MySQL/MariaDB server isn't running on the same machine
    useSSL=false
    # Username to login the database system
    username=""
}
When I completed it well and do /register password its not working. I understand that it should create a table in database? Sorry for my bad english.

**Comment by games647** [comment]
database: The database name in PHPMyAdmin that you want to use
username, password: I think this is obvious
path: IP or domain (i.e. localhost)
type: if you use MySQL/MariaDB write here just MySQL
useSSL: depends on your configuration

**Comment by wallxq** [comment]
I should do table in database for this or its do it automatic?

**Comment by games647** [comment]
the table will be automatically created by FlexibleLogin.

**Comment by wallxq** [comment]
< [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Held$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin >always in console server when player join. I dont know what i bad do..

**Comment by wallxq** [comment]
and this  [Netty Server IO #2/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Auth$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin

**Comment by games647** [comment]
I cannot help you if you only send the first line of the error. I need the complete error.

**Comment by wallxq** [comment]
[16:24:26] [Netty Server IO #4/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Auth$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.16.8, description=Second Auth plugin for Sponge minecraft servers, url=https://github.com/games647/FlexibleLogin, source=C:\Users\wall\Desktop\689726.wom\mods\flexiblelogin-0.16.8.jar}
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.FlexibleLogin.isValidName(FlexibleLogin.java:237) ~[FlexibleLogin.class:?]
        at com.github.games647.flexiblelogin.listener.ConnectionListener.onPlayerAuth(ConnectionListener.java:97) ~[ConnectionListener.class:?]
        at org.spongepowered.common.event.listener.AuthListener_ConnectionListener_onPlayerAuth14.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:339) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:604) [pc.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.handler$fireAuthEventOffline$zjl000(NetHandlerLoginServer.java:620) [pc.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147316_a(NetHandlerLoginServer.java:162) [pc.class:?]
        at net.minecraft.network.login.client.CPacketLoginStart.func_148833_a(SourceFile:33) [mm.class:?]
        at net.minecraft.network.login.client.CPacketLoginStart.func_148833_a(SourceFile:10) [mm.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [gw.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:?]
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:601) [ox.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [IdleStateHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [DefaultChannelPipeline$HeadContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [DefaultChannelPipeline.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[16:24:26] [Netty Server IO #4/INFO] [FML]: Client protocol version 2
[16:24:26] [Netty Server IO #4/INFO] [FML]: Client attempting to join with 7 mods : minecraft@1.12.2,mercurius_updater@1.0,FML@8.0.99.99,forge@14.23.2.2619,redstonepaste@1.7.5,mcp@9.42,naturescompass@1.5.0
[16:24:26] [Netty Server IO #4/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, flexiblelogin, nucleus] at CLIENT
[16:24:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[16:24:26] [Server thread/INFO]: wallXQ[/127.0.0.1:53731] logged in with entity id 260 in world(0) at (-1353.126501487886, 63.0, 1416.7242246430571)
[16:24:27] [pool-3-thread-2/ERROR] [Sponge]: The Scheduler tried to run the task flexiblelogin-A-13 owned by Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.16.8, description=Second Auth plugin for Sponge minecraft servers, url=https://github.com/games647/FlexibleLogin, source=C:\Users\wall\Desktop\689726.wom\mods\flexiblelogin-0.16.8.jar}, but an error occured.
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.listener.ConnectionListener.onAccountLoaded(ConnectionListener.java:121) ~[ConnectionListener.class:?]
        at com.github.games647.flexiblelogin.listener.ConnectionListener.lambda$onPlayerJoin$1(ConnectionListener.java:90) ~[ConnectionListener.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[16:24:27] [Server thread/INFO]: wallXQ joined the game
[16:24:28] [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Held$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.16.8, description=Second Auth plugin for Sponge minecraft servers, url=https://github.com/games647/FlexibleLogin, source=C:\Users\wall\Desktop\689726.wom\mods\flexiblelogin-0.16.8.jar}
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.listener.prevent.AbstractPreventListener.checkLoginStatus(AbstractPreventListener.java:56) ~[AbstractPreventListener.class:?]
        at com.github.games647.flexiblelogin.listener.prevent.PreventListener.onInventoryChange(PreventListener.java:147) ~[PreventListener.class:?]
        at org.spongepowered.common.event.listener.ChangeInventoryEventListener_PreventListener_onInventoryChange28.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.tracking.phase.packet.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:94) [SwitchHotbarScrollState.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.tracking.phase.packet.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:51) [SwitchHotbarScrollState.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:211) [PhaseTracker.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392) [PhaseContext.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[16:24:29] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.16.8, description=Second Auth plugin for Sponge minecraft servers, url=https://github.com/games647/FlexibleLogin, source=C:\Users\wall\Desktop\689726.wom\mods\flexiblelogin-0.16.8.jar}
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.listener.prevent.AbstractPreventListener.checkLoginStatus(AbstractPreventListener.java:56) ~[AbstractPreventListener.class:?]
        at com.github.games647.flexiblelogin.listener.prevent.PreventListener.onPlayerMove(PreventListener.java:89) ~[PreventListener.class:?]
        at org.spongepowered.common.event.listener.MoveEntityEventListener_PreventListener_onPlayerMove19.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.network.NetHandlerPlayServer.redirect$throwMoveEvent$zik000(NetHandlerPlayServer.java:2281) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:462) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) [lk$a.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[16:24:29] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.16.8, description=Second Auth plugin for Sponge minecraft servers, url=https://github.com/games647/FlexibleLogin, source=C:\Users\wall\Desktop\689726.wom\mods\flexiblelogin-0.16.8.jar}
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.listener.prevent.AbstractPreventListener.checkLoginStatus(AbstractPreventListener.java:56) ~[AbstractPreventListener.class:?]
        at com.github.games647.flexiblelogin.listener.prevent.PreventListener.onPlayerMove(PreventListener.java:89) ~[PreventListener.class:?]
        at org.spongepowered.common.event.listener.MoveEntityEventListener_PreventListener_onPlayerMove19.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.network.NetHandlerPlayServer.redirect$throwMoveEvent$zik000(NetHandlerPlayServer.java:2281) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:462) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) [lk$b.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

**Comment by games647** [comment]
This means it failed to setup a connection to the database.

**Comment by games647** [comment]
There should be an error before that.

**Comment by wallxq** [comment]
I install xammpp and do it on localhost and works than i think mydatabase at server isnt good work :) thanks for help.
