### ISSUE TITLE
Email recovery NoSuchProvider and UnsupportedDataType

### ISSUE THREAD

**Issue by 1241534371** [games647/FlexibleLogin#125]
@games647 
/forgot
![1](https://user-images.githubusercontent.com/35589850/37916427-6106a6e2-314e-11e8-9cce-11b75b01fbd4.png)

**Comment by games647** [comment]
Which version do you run?

**Comment by 1241534371** [comment]
SpongeVanilla VERSION：1.12.2-7.1.0-BETA-33
FlexibleLogin VERSION：0.17.2

**Comment by games647** [comment]
Please try a dev-build from here: https://ci.codemc.org/job/Games647/job/FlexibleLogin/

**Comment by 1241534371** [comment]
![1](https://user-images.githubusercontent.com/35589850/38000242-392dc554-3259-11e8-9086-d37db3e8366e.png)

**Comment by games647** [comment]
Please try the newer build too.

**Comment by 1241534371** [comment]
`[18:29:23 ERROR] [Sponge]: Error occurred while executing command 'forgot' for source EntityPlayerMP['666666'/364, l='wo
rld', x=55.50, y=81.00, z=283.50]: com/sun/mail/util/MailLogger
java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
        at javax.mail.Session.initLogger(Session.java:261) ~[flexiblelogin-0.18.jar:?]
        at javax.mail.Session.<init>(Session.java:245) ~[flexiblelogin-0.18.jar:?]
        at javax.mail.Session.getDefaultInstance(Session.java:356) ~[flexiblelogin-0.18.jar:?]
        at javax.mail.Session.getDefaultInstance(Session.java:396) ~[flexiblelogin-0.18.jar:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.buildSession(ForgotPasswordCommand.java:155)
 ~[ForgotPasswordCommand.class:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.prepareSend(ForgotPasswordCommand.java:117)
~[ForgotPasswordCommand.class:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.execute(ForgotPasswordCommand.java:105) ~[Fo
rgotPasswordCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-7.1.0
-BETA-33]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatch
er.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandMa
nager.class:1.12.2-7.1.0-BETA-33]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.1
.0-BETA-33]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkn000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.
2-7.1.0-BETA-33]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(SourceFile:4149) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1580) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`

**Comment by games647** [comment]
Which build number do you tried?

**Comment by 1241534371** [comment]
#40
[https://ci.codemc.org/job/Games647/job/FlexibleLogin/40/](url)
@games647

**Comment by games647** [comment]
Okay, that's crazy the LaunchWrapper in SpongeVanilla ignores all classes that are in a **sun.* packages. So please try the next build.

**Comment by 1241534371** [comment]
![1](https://user-images.githubusercontent.com/35589850/38247649-a06033be-3778-11e8-8ce4-20f1fe476e71.png)
New password
My English is not good.
新密码应该如何设置

**Comment by 1241534371** [comment]
@games647 
THX，it's fine now. The function of retrieving the password through e-mail has been repaired.
