### ISSUE TITLE
Latest Dev Build throws error when setting email recovery to true

### ISSUE THREAD

**Issue by Aersaud** [games647/FlexibleLogin#129]
```
[Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.18-SNAPSHOT, description=Second Auth plugin for Sponge Minecraft servers, url=https://github.com/games647/FlexibleLogin, authors=[games647, Toranktto, frogocomics, sgdc3, nalimleinad], source=/opt/mscs/worlds/TKM-MadCraft/./mods/plugins/flexiblelogin-0.18-SNAPSHOT.jar}
java.lang.NullPointerException: null
	at com.github.games647.flexiblelogin.config.serializer.WorldSerializer.deserialize(WorldSerializer.java:50) ~[WorldSerializer.class:?]
	at com.github.games647.flexiblelogin.config.serializer.WorldSerializer.deserialize(WorldSerializer.java:39) ~[WorldSerializer.class:?]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:85) ~[spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar:1.12.2-2655-7.1.0-BETA-3065]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar:1.12.2-2655-7.1.0-BETA-3065]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:258) ~[spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar:1.12.2-2655-7.1.0-BETA-3065]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:85) ~[spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar:1.12.2-2655-7.1.0-BETA-3065]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:148) ~[spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar:1.12.2-2655-7.1.0-BETA-3065]
	at com.github.games647.flexiblelogin.config.Settings.loadMapper(Settings.java:121) ~[Settings.class:?]
	at com.github.games647.flexiblelogin.config.Settings.load(Settings.java:108) ~[Settings.class:?]
	at com.github.games647.flexiblelogin.FlexibleLogin.init(FlexibleLogin.java:185) ~[FlexibleLogin.class:?]
	at com.github.games647.flexiblelogin.FlexibleLogin.onPreInit(FlexibleLogin.java:115) ~[FlexibleLogin.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_FlexibleLogin_onPreInit5.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:369) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:407) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:391) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2655-7.1.0-BETA-3065]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:244) [SpongeMod.class:1.12.2-2655-7.1.0-BETA-3065]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
Trying to set up email password reset, and getting this error. This disables the login system completely.

Sponge Version: spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar
Forge: forge-1.12.2-14.23.3.2655-universal.jar

**Comment by games647** [comment]
I pushed a new commit which reverts it to the old behavior.

**Comment by Aersaud** [comment]
Awesome will test tonight!

**Comment by Aersaud** [comment]
Ok so I tested it and its sending the email, however the password in the email is showing up as some sort of foreign characters.
```
New password for [REDACTED] on Minecraft server 127.0.0.1: ｹউ路瘒퀵੎饜⢁倘⥙呓䡨㴤�
```

**Comment by games647** [comment]
@Aersaud  You mean English characters?

**Comment by games647** [comment]
Ok I found the source.
