### ISSUE TITLE
/fl register gives "Error creating hash"

### ISSUE THREAD

**Issue by gryffus** [games647/FlexibleLogin#132]
This might be regression of #124

```
[01:12:01] [Netty Epoll Server IO #0/INFO] [FML]: Client protocol version 2
[01:12:01] [Netty Epoll Server IO #0/INFO] [FML]: Client attempting to join with 8 mods : minecraft@1.12.2,ultimate_unicorn_mod@1.5.16,customspawner@3.11.4,FML@8.0.99.99,forge@14.23.3.2655,mocreatures@12.0.4,mcp@9.42,ebwizardry@4.1.1
[01:12:01] [Netty Epoll Server IO #0/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, discordintegration, flexiblelogin, thutessentials, thutperms] at CLIENT
[01:12:02] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[01:12:02] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: test12345[/178.77.232.130:42004] logged in with entity id 3378 in Unicorn world(0) at (-229.07563665118118, 74.0, 257.0481782256657)
[01:12:02] [Server thread/INFO] [ebwizardry]: Synchronising spell glyph data for test12345
[01:12:02] [Server thread/INFO] [ebwizardry]: Synchronising config settings for test12345
[01:12:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: test12345 joined the game
```

```
> /flexiblelogin register test12345 test
[01:12:10] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Cannot force register player. That player is online
[01:12:13] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: test12345 lost connection: Disconnected
[01:12:13] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: test12345 left the game
```

```
> /flexiblelogin register test12345 test
[01:12:16] [pool-3-thread-8/ERROR] [flexiblelogin]: Error creating hash
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.Database.createAccount(Database.java:267) ~[Database.class:?]
        at com.github.games647.flexiblelogin.tasks.ForceRegTask.run(ForceRegTask.java:61) ~[ForceRegTask.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2655-7.1.0-BETA-3100]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3100]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_172]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[01:12:16] [pool-3-thread-8/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Error executing command, see console.
```

running on:
md5sum ./forge-1.12.2-14.23.3.2655-universal.jar 
01bfe029f75be3039dccdc80ab29a329  ./forge-1.12.2-14.23.3.2655-universal.jar
md5sum ./flexiblelogin-0.17.3.jar 
dbd557f89eb83fa559ac411972c863fe  ./flexiblelogin-0.17.3.jar

**Comment by games647** [comment]
This is already fixed in a dev-build

**Comment by GershonR** [comment]
I'm getting this error with 0.17.4, which was released July 7, after the dev build

**Comment by games647** [comment]
@GershonR 

> I'm getting this error with 0.17.4, which was released July 7, after the dev build

Please open a new ticket with the exact error message. So I can see the line numbers.
