### ISSUE TITLE
SQLConfig

### ISSUE THREAD

**Issue by juzhijian** [games647/FlexibleLogin#135]
[03:35:06] [Server thread/ERROR] [flexiblelogin]: Error loading the configuration
ninja.leaping.configurate.objectmapping.ObjectMappingException: No zero-arg constructor is available for class class com.github.games647.flexiblelogin.config.node.SQLConfig$Type but is required to construct new instances!
	at ninja.leaping.configurate.objectmapping.ObjectMapper.constructObject(ObjectMapper.java:231) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.ObjectMapper.bindToNew(ObjectMapper.java:268) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:268) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:94) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.deserialize(TypeSerializers.java:268) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:94) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar:1.12.2-2705-7.1.0-BETA-3243]
	at com.github.games647.flexiblelogin.config.Settings.loadMapper(Settings.java:121) [Settings.class:?]
	at com.github.games647.flexiblelogin.config.Settings.load(Settings.java:104) [Settings.class:?]
	at com.github.games647.flexiblelogin.FlexibleLogin.init(FlexibleLogin.java:185) [FlexibleLogin.class:?]
	at com.github.games647.flexiblelogin.FlexibleLogin.onPreInit(FlexibleLogin.java:115) [FlexibleLogin.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_FlexibleLogin_onPreInit87.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3243]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3243]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3243]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3243]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:223) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3243]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:267) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3243]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

The Sponge Version:spongeforge-1.12.2-2705-7.1.0-BETA-3243.jar
The Forge Version:forge-1.12.2-14.23.4.2705-universal

**Comment by games647** [comment]
Which plugin version do you use?

**Comment by juzhijian** [comment]
flexiblelogin-0.17.3.jar
