### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Heriptik** [games647/FlexibleLogin#146]
Hello, it's not possible to /flexiblelogin register player

Command don't work

**Comment by games647** [comment]
Please explain. Never write only "don't work". Please write how you invoked the command and what was the outcome?

**Comment by Heriptik** [comment]
I execute this command : /flexiblelogin register Test 123456 

Flexiblelogin version **0.17.4**

Error see console 

[09:17:26] [pool-3-thread-2/ERROR] [flexiblelogin]: Error creating hash
java.lang.NullPointerException: null
        at com.github.games647.flexiblelogin.Database.createAccount(Database.java:267) ~[Database.class:?]
        at com.github.games647.flexiblelogin.tasks.ForceRegTask.run(ForceRegTask.java:61) ~[ForceRegTask.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3477]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
