### ISSUE TITLE
Find some problems in DateTimeParse

### ISSUE THREAD

**Issue by RoFatNya** [games647/FlexibleLogin#151]
I find some problems in login,it might be the time text format is not right. Hope your reply,thx. :)
It's Log
[01:58:58] [pool-3-thread-2/ERROR] [Sponge]: The Scheduler tried to run the task flexiblelogin-A-44 owned by Plugin{id=flexiblelogin, name=FlexibleLogin, version=0.17.4, description=Second Auth plugin for Sponge Minecraft servers, url=https://github.com/games647/FlexibleLogin, source=.\mods\[Plugin]flexiblelogin-0.17.4.jar}, but an error occured.
java.time.format.DateTimeParseException: Text '1547226690960' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source) ~[?:1.8.0_162]
        at java.time.format.DateTimeFormatter.parse(Unknown Source) ~[?:1.8.0_162]
        at java.time.LocalDateTime.parse(Unknown Source) ~[?:1.8.0_162]
        at com.github.games647.flexiblelogin.Account.parseTimestamp(Account.java:155) ~[Account.class:?]
        at com.github.games647.flexiblelogin.Account.<init>(Account.java:86) ~[Account.class:?]
        at com.github.games647.flexiblelogin.Database.loadAccount(Database.java:210) ~[Database.class:?]
        at com.github.games647.flexiblelogin.Database.loadAccount(Database.java:193) ~[Database.class:?]
        at com.github.games647.flexiblelogin.listener.ConnectionListener.onAccountLoaded(ConnectionListener.java:127) ~[ConnectionListener.class:?]
        at com.github.games647.flexiblelogin.listener.ConnectionListener.lambda$loadAccountOnJoin$4(ConnectionListener.java:122) ~[ConnectionListener.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.4]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by CalElFe** [comment]
me too, the same error occurred.
