### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by qijidaren** [games647/FlexibleLogin#68]
[20:29:06] [Server thread/INFO] [nucleus/]: _qiji ran the command: /login qwe321
[20:29:06] [pool-2-thread-1/ERROR] [flexiblelogin/sponge]: Unexpected error while password checking
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.charAt(Unknown Source) ~[?:1.8.0_131]
	at com.github.games647.flexiblelogin.hasher.BcryptHasher.checkPassword(BcryptHasher.java:42) ~[BcryptHasher.class:?]
	at com.github.games647.flexiblelogin.Account.checkPassword(Account.java:89) ~[Account.class:?]
	at com.github.games647.flexiblelogin.tasks.LoginTask.run(LoginTask.java:71) ~[LoginTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2281-5.2.0-BETA-2274]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2274]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by qijidaren** [comment]
If you register as aaa, you can't register AAA

**Comment by qijidaren** [comment]
I want to ，register for aaa, can't register AAA

**Comment by games647** [comment]
Fixed with last commit
