### ISSUE TITLE
Cannot register with SQLite database

### ISSUE THREAD

**Issue by hexchain** [games647/FlexibleLogin#9]
Packages in use:
forge-1.8-11.14.4.1563-universal.jar
spongeforge-1.8-1577-3.0.0-BETA-1000.jar
FlexibleLogin.jar (0.3.2)

When attempting to register:
```
[19:19:26] [pool-2-thread-1/ERROR] [flexiblelogin]: Error registering account
java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: users.UserID)
        at org.sqlite.core.DB.newSQLException(DB.java:890) ~[DB.class:1.8-1577-3.0.0-BETA-1000]
        at org.sqlite.core.DB.newSQLException(DB.java:901) ~[DB.class:1.8-1577-3.0.0-BETA-1000]
        at org.sqlite.core.DB.execute(DB.java:810) ~[DB.class:1.8-1577-3.0.0-BETA-1000]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:50) ~[JDBC3PreparedStatement.class:1.8-1577-3.0.0-BETA-1000]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[ProxyPreparedStatement.class:1.8-1577-3.0.0-BETA-1000]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:1.8-1577-3.0.0-BETA-1000]
        at com.github.games647.flexiblelogin.Database.createAccount(Database.java:272) ~[Database.class:?]
        at com.github.games647.flexiblelogin.tasks.RegisterTask.run(RegisterTask.java:33) ~[RegisterTask.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$9(Task.java:138) ~[Task$Builder.class:1.8-1577-3.0.0-BETA-1000]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$55(SchedulerBase.java:177) ~[SchedulerBase.class:1.8-1577-3.0.0-BETA-1000]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by games647** [comment]
Oh, you're right. Looks like the table setup is incorrect.

**Comment by hexchain** [comment]
Wow that's real quick, thank you!
