### ISSUE TITLE
MailLogger error

### ISSUE THREAD

**Issue by Jengas** [games647/FlexibleLogin#92]
![image](https://user-images.githubusercontent.com/14033756/34267756-553c8f4a-e67e-11e7-9da9-d615e1d04b90.png)

`[18:39:04 ERROR] [Sponge]: Error occurred while executing command 'forgotpassword' for source EntityPlayerMP['Jengas'/1525, l='world', x=-557,46, y=72,70, z=-574,95]: com/sun/mail/util/MailLogger
java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger
        at javax.mail.Session.initLogger(Session.java:261) ~[flexiblelogin-0.16.5.jar:?]
        at javax.mail.Session.<init>(Session.java:245) ~[flexiblelogin-0.16.5.jar:?]
        at javax.mail.Session.getDefaultInstance(Session.java:356) ~[flexiblelogin-0.16.5.jar:?]
        at javax.mail.Session.getDefaultInstance(Session.java:396) ~[flexiblelogin-0.16.5.jar:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.buildSession(ForgotPasswordCommand.java:142) ~[ForgotPasswordCommand.class:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.prepareSend(ForgotPasswordCommand.java:106) ~[ForgotPasswordCommand.class:?]
        at com.github.games647.flexiblelogin.commands.ForgotPasswordCommand.execute(ForgotPasswordCommand.java:98) ~[ForgotPasswordCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-7.0.0-BETA-377]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-7.0.0-BETA-377]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-377]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-7.0.0-BETA-377]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjl000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-377]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4180) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        ... 28 more`

**Comment by games647** [comment]
What other plugins/mods do you have? Is there another plugin that uses the mail system?

**Comment by Jengas** [comment]
I am not sure 
![image](https://user-images.githubusercontent.com/14033756/34301134-87b0289e-e72b-11e7-9f95-ea4596623b28.png)

**Comment by games647** [comment]
Could you please try 0.16.6

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/34302365-cb4c7d00-e730-11e7-8af6-a01cad4d0b51.png)
Mabe because I have API 7. And your plugin is for API 5
![image](https://user-images.githubusercontent.com/14033756/34302385-e0586ad8-e730-11e7-9a16-a7aee5727e2c.png)

**Comment by games647** [comment]
No it's unrelated to the Sponge version and it's now a different error. So it seems to be fixed.

Could you post the full log for this.

**Comment by Jengas** [comment]
`[15:57:03] [pool-3-thread-5/ERROR] [flexiblelogin]: Error sending email
flexiblelogin.javax.mail.NoSuchProviderException: smtp
	at flexiblelogin.javax.mail.Session.getService(Session.java:842) ~[Session.class:?]
	at flexiblelogin.javax.mail.Session.getTransport(Session.java:772) ~[Session.class:?]
	at flexiblelogin.javax.mail.Session.getTransport(Session.java:713) ~[Session.class:?]
	at flexiblelogin.javax.mail.Session.getTransport(Session.java:693) ~[Session.class:?]
	at com.github.games647.flexiblelogin.tasks.SendEmailTask.run(SendEmailTask.java:56) ~[SendEmailTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.0.0-BETA-377]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-7.0.0-BETA-377]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[15:57:09] [Server thread/DEBUG] [io.netty.util.internal.ThreadLocalRandom]: -Dio.netty.initialSeedUniquifier: 0x76588a2d4958e2eb`

**Comment by games647** [comment]
I meant the full server log.

**Comment by Jengas** [comment]
https://gist.github.com/Jengas/656fe3b60d0670758136a7b2996cdc03

**Comment by games647** [comment]
Please try it with 0.16.7 again.

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/34319043-e2bc71d8-e7d6-11e7-8327-ecb1b4b1be2d.png)
Maybe better if you can contact me in DM Discord? 

> Jengas#0604

**Comment by games647** [comment]
Should be fixed now.
